/**
 * Migration runner.
 *
 * Usage:
 *   pnpm migrate              # apply pending migrations
 *   pnpm migrate:generate     # generate new migration from schema diff
 *
 * Reads the schema + migrations directory configured in drizzle.config.ts
 * and applies any unapplied migrations to the SQLite database identified
 * by DATABASE_URL (default: ./dev.db).
 *
 * The actual migration SQL lives in ./migrations/*.sql (generated by
 * `pnpm migrate:generate`). This script wraps Drizzle's migrate().
 */

import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { createDb } from './db';

try {
  const db = createDb();
  migrate(db, { migrationsFolder: './migrations' });
  console.log('[migrate] All migrations applied successfully.');
} catch (err: unknown) {
  console.error('[migrate] Migration failed:', err);
  process.exit(1);
}
