/**
 * tests/fixtures/seed.ts — deterministic seed + PRNG for synthetic fixtures.
 *
 * SEC-001 AR-4 ("Synthetic Fixtures Only") requires all test data to be
 * generated by the test framework, never copied from a real vault, and
 * reproducible. This module is the single source of the fixed seed and the
 * deterministic PRNG that every bulk/varied factory shares, so a test can rely
 * on stable output while still getting varied — but synthetic — values.
 *
 * SECRET MATERIAL (passwords, keys, salts, nonces, ciphertext) is NOT derived
 * from this PRNG. It comes from `node:crypto` randomBytes (see ./crypto.ts) so
 * that no secret is ever hard-coded, memorized, or accidentally reproducible —
 * the one place determinism must not apply.
 */

/**
 * Fixed seed constant (AR-4: "fixed seed for determinism"). Do not change
 * without a recorded reason — tests that rely on the bulk generators depend on
 * the exact sequences this produces.
 */
export const FIXTURE_SEED = 0x5eed2026;

/**
 * mulberry32 — a small, fast, well-known 32-bit PRNG. Deterministic for a
 * given seed. NOT cryptographically secure: it is used ONLY for structured
 * fake data (bulk names, usernames, tags), never for secret material.
 */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A factory-fresh deterministic PRNG. Call once per fixture and thread the
 *  returned function through the bulk generators that need a stable sequence. */
export function seededRandom(seed: number = FIXTURE_SEED): () => number {
  return mulberry32(seed);
}

/** Deterministic integer in [min, max). */
export function int(rng: () => number, min: number, max: number): number {
  return Math.floor(rng() * (max - min)) + min;
}

/** Deterministic pick from a list. */
export function pick<T>(rng: () => number, items: readonly T[]): T {
  return items[int(rng, 0, items.length)];
}
